name: Test

on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - "ready_for_review"
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install lemon
          brew install tcl-tk
          curl -fsSL https://bun.sh/install | bash

      - name: Run tests
        run: make test
