name: Test

on:
  workflow_dispatch:
  push:
    branch: "master"
  pull_request:
    types:
      - "ready_for_review"
      - "opened"
      - "synchronize"
      - "reopened"

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install lemon tcl

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: make test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Run tests
        run: nmake /f Makefile.vc test

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install lemon
          brew install tcl-tk
          brew tap-new $USER/local-sqlite
          brew extract --version=3.46.1 sqlite $USER/local-sqlite
          brew install sqlite@3.46.1

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: |
          export SQLITE_LIB_PATH=/opt/homebrew/Cellar/sqlite@3.46.1/3.46.1/lib/libsqlite3.dylib
          make test
